export const DataEventConst = {
    MOUSE_DOWN: 'mouseDown',
    MOUSE_UP: 'mouseUp',
    MOUSE_MOVE: 'mouseMove',
    MOUSE_MOVE_ALPHA: 'mouseMoveAlpha',
    MOUSE_CLICK: 'mouseClick',
    MOUSE_HOVER: 'mouseHover',
    MOUSE_LEAVE: 'mouseLeave',
    WINDOW_RESIZE: 'windowResize',
    WHEEL: 'wheel',
    MAP_UPDATE: 'map_update',
    ADD_ICON: 'add_icon',
    REMOVE_ICON: 'remove_icon',
    LOAD_ICON: 'load_icon',
    HIDE_ICON: 'hide_icon',
    DEACTIVATE_FLOOR_QUESTS_ICON: 'deactivate_floor_quests_icon',
    HIDE_ALL_FLOOR_ICONS: 'hide_all_floor_icons',
    MAP_FLOORS_UPDATE: 'map_floors_update',
    QUEST_UPDATE: 'quest_update',
    QUEST_UPDATE_OW_EVENT: 'quest_update_ow_event',
    QUEST_ACTIVATION: 'quest_activation',
    QUEST_OBJECTIVE_UPDATE: 'quest_objective_update',
    QUEST_DEACTIVATION: 'quest_deactivation',
    QUEST_COMPLETED: 'quest_completed',
    QUEST_TRACKING: 'quest_tracking',
    QUEST_FAILED: 'quest_failed',
    QUEST_UNCOMPLETED: 'quest_uncompleted',
    QUEST_PAGE_REFRESH: 'quest_page_refresh',
    QUEST_MAP_FILTER: 'quest_map_filter',
    DISABLE_QUEST_STATE: 'change_quest_state',
    QUEST_SEARCH_BAR: 'quest_search_bar_event',
    QUEST_AUTOMATION: 'quest_automation',
    LEVEL_CHANGE: 'level_change',
    ZOOM_ON_ICON: 'zoomOnIcon',
    PROGRESSION_CHANGED: 'progressionChanged',
    HIDEOUT_PAGE_STATE_REFRESH: 'hideoutPageStateRefresh',
    HIDEOUT_COMPLETED: 'hideoutCompleted',
    HIDEOUT_ACTIVE: 'hideoutActive',
    HIDEOUT_LEVEL_INACTIVE: 'hideoutLevelIna ctive',
    HIDEOUT_LEVEL_COMPLETED: 'hideoutLevelCompleted',
    HIDEOUT_LEVEL_ACTIVE: 'hideoutLevelActive',
    HIDEOUT_HEADER_CLICK: 'hideoutHeaderClick',
    HIDEOUT_LEVEL_HEADER_CLICK: 'hideoutLevelHeaderClick',
    HIDEOUT_STATION_CLICK: 'hideoutStationClick',
    HIDEOUT_STATION_LAYOUT_HOVER: 'hideoutStationLayoutHover',
    HIDEOUT_STATION_LAYOUT_HOVER_OUT: 'hideoutStationLayoutHoverOut',
    HIDEOUT_STATION_LOGO_HOVER: 'hideoutStationLogoHover',
    HIDEOUT_STATION_LOGO_HOVER_OUT: 'hideoutStationLogoHoverOut',
    HIDEOUT_STATION_LOGO_LEVEL_CLICK: 'hideoutStationLogoHoverClick',
    HIDEOUT_LEVEL_REQUIREMENT_CLICK: 'hideoutLevelRequirementClick',
    HIDEOUT_LEVEL_CRAFT_CLICK: 'hideoutLevelCraftClick',
    HIDEOUT_STATION_NAVIGATION: 'hideoutStationNavigation',
    HIDEOUT_STATION_LEVEL_NAVIGATION: 'hideoutStationLevelNavigation',
    HIDEOUT_STATION_LEVEL_CRAFT_NAVIGATION: 'hideoutStationLevelCraftNavigation',
    HIDEOUT_STATION_LEVEL_REQUIREMENT_NAVIGATION: 'hideoutStationLevelRequirementNavigation',
    HIDEOUT_FILTER_CHANGE: "hideoutFilterChange",
    HIDEOUT_STATION_PAGE_CLOSE: 'hideoutStationPageClose',
    ITEM_STATE_CHANGED: 'itemStateChange',
    ITEM_CLICK: 'itemClick',
    ITEM_PAGE_REFRESH: 'itemPageRefresh',
    
    EDIT_LEVEL: "editLevel",

    EDIT_MODE_CHANGED: 'editModeChanged',
    
}